### ISSUE TITLE
Change fields to Editor JS blocks

### ISSUE THREAD

**Issue by deshetti** [factly/dega-studio#146]
Change the followings fields to a rich-text editor like description fields in category and tag:

- [x] Claimant -> Description
- [x] Claim -> Claim Sources, Review, Review Tagline, Review Sources
- [x] Rating -> Description

**Comment by 96RadhikaJadhav** [comment]
@shreeharsha-factly I would like to work on this. For this issue, for Claim-> Claim Sources, Review, Review Tagline, Review Sources 
What rich-text should be added?
