### ISSUE TITLE
Add gravity:sm to frame the img urls

### ISSUE THREAD

**Issue by deshetti** [factly/dega-studio#174]
Add `gravity:sm` to the imgproxy url. This detects the most “interesting” section of the image and considers it as the center of the resulting image and should be used for all the imgrpoxy URLs.

with gravity:sm -  [https://images.factly.org/f/dega/factly/2020/11/1606852805888_shashi-deshettipng?resize:fill:200:150/gravity:sm](https://images.factly.org/f/dega/factly/2020/11/1606852805888_shashi-deshettipng?resize:fill:200:150/gravity:sm)
without gravity:sm - [https://images.factly.org/f/dega/factly/2020/11/1606852805888_shashi-deshettipng?resize:fill:200:150](https://images.factly.org/f/dega/factly/2020/11/1606852805888_shashi-deshettipng?resize:fill:200:150)

**Comment by 96RadhikaJadhav** [comment]
@deshetti  Could you please assign this issue to me and direct me to the file where it can be changed?

**Comment by shreeharsha-factly** [comment]
@96RadhikaJadhav you can search for url?.proxy in the code  there you can add */gravity:sm* after _resize:fill:200:150_

**Comment by deshetti** [comment]
@shreeharsha-factly @96RadhikaJadhav we should also set the size and gravity:sm at the following places where the image is displayed from a media selector.

- [ ] Create/Edit post - Featured Image
- [ ] Create/Edit category -  Featured Image
- [ ] Create/Edit claimant -  Featured Image

I might have a few from the above list

@96RadhikaJadhav Thanks for the contribution. There is another issue good for beginners if you want to take a stab at: https://github.com/factly/dega-studio/issues/177

**Comment by shreeharsha-factly** [comment]
@deshetti  What should be the  *resize:fill:width:height* ?

**Comment by deshetti** [comment]
We could use the same `resize:fill:200:150` to start with. Is that changeable b/w different components or will it have to be the same size everywhere since it is shared component?

**Comment by shreeharsha-factly** [comment]
It can be changeable and it is not shared.

**Comment by deshetti** [comment]
keep it the same `resize:fill:200:150` for all for now in that case.

**Comment by 96RadhikaJadhav** [comment]
> @shreeharsha-factly @96RadhikaJadhav we should also set the size and gravity:sm at the following places where the image is displayed from a media selector.
> 
> * [ ]  Create/Edit post - Featured Image
> * [ ]  Create/Edit category -  Featured Image
> * [ ]  Create/Edit claimant -  Featured Image
> 
> I might have a few from the above list
> 
> @96RadhikaJadhav Thanks for the contribution. There is another issue good for beginners if you want to take a stab at: factly/dega#233

@deshetti  Thanks for reconsidering me :) . Surely I will take a look at factly/dega#233 and will get back to you.
