### ISSUE TITLE
Change `meta_fields` editor in Category to use Monaco Editor

### ISSUE THREAD

**Issue by deshetti** [factly/dega-studio#352]
We could change the JSON editor that we have for `meta_fields` in `category` to use Monaco Editor. It seems pretty straightforward to import into apps. Here are a few references:

Github: https://github.com/Microsoft/monaco-editor
Monaco Editor Playground (JSON example): https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults
Quick demo of integrating into website: https://www.youtube.com/watch?v=aKtH4o5-5UY

**Comment by shreeharsha-factly** [comment]
The package is too large(80MB) for our use case.

**Comment by deshetti** [comment]
@shreeharsha-factly which package are you referring to?

I have downloaded these four packages that are mentioned in the demo:https://www.youtube.com/watch?v=aKtH4o5-5UY

They all combine to < 3MB. I have downloaded them from here: https://cdnjs.com/libraries/monaco-editor

https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/editor/editor.main.js
https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/loader.min.js
https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/editor/editor.main.min.css
https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/editor/editor.main.nls.min.js

**Comment by shreeharsha-factly** [comment]
@deshetti https://www.npmjs.com/package/monaco-editor
